name: Check and Test

on:
  push:
    branches: 
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  check_and_test:
    runs-on: ubuntu-latest

    env:
      PHP_CS_FIXER_IGNORE_ENV: true

    strategy: 
      fail-fast: false
      matrix:
        include:
          - php: 8.2
          - php: 8.3
          - php: 8.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer update

      - name: Run PHP CS Fixer
        run: bin/php-cs-fixer check

      - name: Run PHPStan
        run: bin/phpstan analyze

      - name: Run Tests
        run: bin/phpunit
